capstone/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^guitar_zone/', include("guitar_zone.urls")),
]

guitar_zone/urls.py
from django.conf.urls import url, include
import sys
# sys.path.append("../")
from django.contrib import admin
from .views import customer_view, guitar_detail_view, guitar_view, home_view, guitar_category_view, order_view, payment_type_view
from .views.customer_view import RegisterViewSet, LoginViewSet
from .views.payment_type_view import add_payment
from .views.rent_out_guitar_view import rent_out_guitar


app_name = 'guitar_zone'

urlpatterns = [
    url(r'^register/', RegisterViewSet.as_view(), name='register'),
    url(r'^register_customer/', customer_view.register_customer, name='register_customer'),
    url(r'^login/', LoginViewSet.as_view(), name='login'),
    url(r'^login_customer/', customer_view.login_customer, name='login_customer'),
    url(r'^logout/', customer_view.logout_customer, name='logout'),
    url(r'^order/', customer_view.logout_customer, name='order'),
    url(r'^account/', customer_view.logout_customer, name='account'),
    url(r'^cart/', order_view.get_guitars_in_cart, name='cart'),
    url(r'^addpayment/', payment_type_view.add_payment, name='addpayment'),
]

urlpatterns += [  url(r'^home/', home_view.get_guitars_and_types, name='home'),
]

urlpatterns += [
    url(r'^guitars/', guitar_view.get_guitars_types_and_count, name='guitars'),
    url(r'^guitartype/(?P<pk>\d+)/', guitar_category_view.get_guitar_type_info, name='guitartype'),
    url(r'^guitardetail/(?P<pk>\d+)/', guitar_detail_view.GuitarDetailView.as_view(), name='guitardetail'),
    url(r'^add_guitar_to_order/(?P<pk>\d+)/', guitar_detail_view.add_guitar_to_order, name='add_guitar_to_order'),
    url(r'^addguitar/', rent_out_guitar, name='addguitar'),
]

guitar_zone/models/customer_model.py
import sqlite3
from django.db import models
from django.contrib.auth.models import User

class Customer(models.Model):
  
    first_name = models.CharField(max_length=240)
    last_name = models.CharField(max_length=240)
    address = models.CharField(max_length=240)
    city = models.CharField(max_length=55)
    state_province = models.CharField(max_length=55)
    country = models.CharField(max_length=55)
    postal_code = models.CharField(max_length=9)
    email = models.EmailField(max_length=55)
    user = models.OneToOneField(User)

    class Meta:
        verbose_name_plural = "Customer"

    def __str__(self):
        return '{} {} {} {} {} {} {} {} {} {}'.format(self.first_name, self.last_name, self.address, self.city, self.state_province, self.country, self.postal_code, self.email, self.user.username , self.user.password)

    def get_first_name(self):
        return self.first_name

    def get_last_name(self):
        return self.last_name

    def get_address(self):
        return self.address

    def get_city(self):
        return self.city

    def get_state_province(self):
        return self.state_province

    def get_country(self):
        return self.country

    def get_postal_code(self):
        return self.postal_code

    def get_email(self):
        return self.email

    def get_password(self):
        return self.user.password

    def get_full_name(self):
        full_name = self.first_name + " " + self.last_name
        return full_name

guitar_zone/models/guitar_model.py
import sqlite3
from django.db import models
from . import customer_model, guitar_type_model


class Guitar(models.Model):
    ''' 
    Product Class contains the essential fields and behaviors of the data stored in a product.

    Method List:
    -get_product_name
    -get_description
    -get_price
    -get_quantity
    -purchase_productitemQty):
    -get_purchased
    -get_seller
    -get_product_type

    Argument List:
    -models.Model: This argument allows the class to access field types.

    '''
    name = models.CharField(max_length=75)
    description = models.CharField(max_length=250)
    price = models.DecimalField(max_digits = 10, decimal_places = 2)
    quantity = models.IntegerField(default=1)
    seller = models.ForeignKey(customer_model.Customer)
    guitar_type = models.ForeignKey(guitar_type_model.GuitarType)
    pub_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '{}'.format(self.guitar_type)

    def get_guitar_name(self):
        return self.name

    def get_description(self):
        return self.description

    def set_description(self, new_description):
        self.description = new_description
        return new_description

    def get_price(self):
        return self.price

    def get_quantity(self):
        return self.quantity

    def purchase_product(self, itemQty):
        if itemQty > self.quantity:
            print("We don't have that kind of quantity for {}(s). Only {} available.".format(self.name, self.quantity))
        else:
            self.quantity = self.quantity - itemQty
            return self.quantity

    def seller_set_quantity(self, new_quantity):
        self.quantity = new_quantity
        return self.quantity

    def get_purchased(self):
        return self.purchased

    def get_seller(self):
        return self.seller

    def get_guitar_type(self):
        return self.guitar_type

guitar_zone/models/guitar_type_model.py
from django.db import models

class GuitarType(models.Model):
    """
    Stores a single product type, "label_name"
    author: Richie Van Sickle
    """
    label_name = models.CharField(max_length=55)

    def get_guitar_type_label(self):
        """
        Returns the label_name
        author: Richie Van Sickle
        """
        return self.label_name 

    def __str__(self):
        return '{}'.format(self.label_name)

guitar_zone/models/order_items_model.py
from django.db import models
from . import order_model, guitar_model


class OrderItems(models.Model):
    guitar = models.ForeignKey(guitar_model.Guitar, on_delete=models.CASCADE)
    order = models.ForeignKey(order_model.GuitarZoneOrder, on_delete=models.CASCADE)

guitar_zone/models/order_model.py
from django.db import models
from . import customer_model, payment_type_model, guitar_model

class GuitarZoneOrder(models.Model):
    """
    Stores a Rent Order
    Method List:
    -set_order_is_complete
    -get_order_is_complete
    -get_products_in_cart
    Argument List:
    -models.Model Allows the class to access field types
    """
    customer = models.ForeignKey(customer_model.Customer, on_delete=models.CASCADE)
    payment_type = models.ForeignKey(payment_type_model.PaymentType, on_delete=models.CASCADE, null = True)
    order_is_complete = models.BooleanField()
    guitar = models.ManyToManyField(guitar_model.Guitar, through = 'OrderItems')

    def set_order_is_complete(self):
        self.order_is_complete = 1
        return self.order_is_complete

    def get_order_is_complete(self):
        return self.order_is_complete

guitar_zone/forms.py
from django import forms
from guitar_zone.models.payment_type_model import PaymentType
from guitar_zone.models.guitar_model import Guitar
from django.utils.translation import ugettext_lazy as _

class PaymentTypeForm(forms.ModelForm):

    class Meta:
        model = PaymentType
        help_texts = {
            'card_type': _('Card Type:'),
            'card_number': _('Card Number:'),
            'cvv': _('3 digit cvv '),
            'expiration': _('Exp. Date:'),
            'name_on_card': _('Full Name on Card:')
        }
        fields = ('card_type', 'card_number', 'cvv', 'expiration', 'name_on_card')

class RentOutGuitarForm(forms.ModelForm):

    class Meta:
        model = Guitar
        help_texts = {
            'name': _('Guitar Make/Model:'),
            'description': _('Description:'),
            'price': _('Price/day:'),
            'guitar_type': _('Choose Category:')
        }
        fields = ('name', 'description', 'price', 'guitar_type')

guitar_zone/views/customer_view.py
from django.contrib.auth.models import User, Group
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import logout, login, authenticate
from django.http import HttpResponse, HttpResponseRedirect
import sys
sys.path.append("../")
from guitar_zone.models import customer_model


class RegisterViewSet(TemplateView):

    template_name = "guitar_zone/register.html"

def register_customer(request):
    data = request.POST
    user = User.objects.create_user(
        username = data['username'],
        password = data['password'],
        )
    customer = customer_model.Customer.objects.create(
        first_name = data['first_name'],
        last_name = data['last_name'],
        address = data['address'],
        city = data['city'],
        state_province = data['state_province'],
        country = data['country'],
        postal_code = data['postal_code'],
        email = data['email'],
        user = user
    )
    return login_customer(request)

class LoginViewSet(TemplateView):

    template_name = "guitar_zone/login.html"

def login_customer(request):
    data = request.POST
    username = data["username"]
    password = data['password']
    user = authenticate(
        username = username,
        password = password
    )
    if user is not None:
        login(request = request, user = user)
        return HttpResponseRedirect(redirect_to='/guitar_zone/home')
    else:
        return HttpResponseRedirect(redirect_to='/guitar_zone/login')


def logout_customer(request):
    logout(request)
    return HttpResponseRedirect(redirect_to='/guitar_zone/login')


    

guitar_zone/views/guitar_category_view.py
from django.contrib.auth.models import User, Group
from django.views import generic
from django.shortcuts import render
from django.views.generic.base import TemplateView
import sys
sys.path.append("../")
from guitar_zone.models.guitar_model import Guitar
from guitar_zone.models.guitar_type_model import GuitarType


def get_guitar_type_info(request, pk):
    guitar_type = GuitarType.objects.filter(id=pk)
    guitars = Guitar.objects.filter(guitar_type=pk)
    return render(request, 'guitar_zone/guitar_category.html', {
        'guitar_list': guitars,
        'guitar_type': guitar_type[0]
            })

guitar_zone/views/guitar_detail_view.py
from django.contrib.auth.models import User, Group
from django.views import generic
import sys
sys.path.append("../")
from guitar_zone.models import GuitarType, Guitar, GuitarZoneOrder, Customer, OrderItems
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import logout, login, authenticate
from guitar_zone import models


class GuitarDetailView(DetailView):
    model = Guitar

def get_guitar_detail(request):
    guitar_detail_view = Guitar.objects.filter(id=id)
    return render(request, 'guitar_zone/guitar_detail.html', {'guitar': guitar_detail_view})

def add_guitar_to_order(request, pk):
    print("REQUEST IS HERE:::::::::: ", request)
    guitar = Guitar.objects.get(id = pk)


    try:
        order_pk = GuitarZoneOrder.objects.get(customer = request.user.id)
        new_order = GuitarZoneOrder.objects.get(id = order_pk.id, order_is_complete = False)
    except:
        customer = Customer.objects.get(user = request.user)
        new_order = GuitarZoneOrder.objects.create(order_is_complete = False, customer = customer, payment_type = None)
        new_order.save()

    orderitem = models.OrderItems(guitar=guitar, order=new_order)
    orderitem.save()

    return HttpResponseRedirect(redirect_to='/guitar_zone/guitars/')

guitar_zone/views/guitar_view.py
from django.contrib.auth.models import User, Group
from django.views import generic
from django.shortcuts import render
from django.views.generic.base import TemplateView
import sys
sys.path.append("../")
from guitar_zone.models import guitar_model, guitar_type_model


def get_guitars_types_and_count(request):
    guitar_type_queryset = guitar_type_model.GuitarType.objects.all()
    g_queryset = []

    for gt in guitar_type_queryset:
        g = guitar_model.Guitar.objects.filter(guitar_type=gt.pk).order_by('pub_date')

        guitar_type_info = {
            'type_id': gt.pk, 
            'type_label_name': gt.label_name,
            'g_list': g.reverse()[:20],
            'count': g.count()
        }

        g_queryset.append(guitar_type_info)
        print("PLIST:", guitar_type_info['g_list'])

    # print("PRODUCT QUERYSET", p_queryset)

    return render(request, 'guitar_zone/guitars.html', {
        'guitars_info': g_queryset
    }) 

guitar_zone/views/home_view.py
from django.contrib.auth.models import User, Group 
from django.views import generic
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.db.models import Q
import sys
sys.path.append("../")
from guitar_zone.models import guitar_model, guitar_type_model


def get_guitars_and_types(request):
    guitar_type_queryset = guitar_type_model.GuitarType.objects.all()
    guitar_queryset = []

    for gt in guitar_type_queryset:
        g = guitar_model.Guitar.objects.filter(guitar_type=gt.pk).order_by('pub_date').reverse()[:2]
        guitar_queryset.append(g)


    return render(request, 'guitar_zone/home.html', {
        'guitar':guitar_queryset,
        'guitar_type':guitar_type_queryset
    })

guitar_zone/views/order_view.py
from django.shortcuts import render
from django.contrib.auth.models import User, Group
from django.http import HttpResponse
from django.views import generic
from django.views.generic.base import TemplateView
import sqlite3
import sys
sys.path.append("../")
from guitar_zone.models import order_model, payment_type_model
from collections import Counter

class BangazonOrderView(TemplateView):
    template_name = 'guitar_zone/templates/order.html'

def get_guitars_in_cart(request):
    """
    Returns Orders in a list form
    """
    print('This is the request for user', request.user.id)
    # <--- This gets order related to logged in Customer
    active_order = order_model.GuitarZoneOrder.objects.get(customer__user = request.user)

    # <--- Gets all guitars on the active order
    guitar_on_order = active_order.guitar.all()
    print("This is the first product: ", guitar_on_order[0].name)

    # <--- var to hold total price
    total_price = 0
    for guitar in guitar_on_order:
        total_price += guitar.price

    # <--- Create and update array for guitars on order with name, quantity and total price/item
    guitar_array = []
    guit = Counter(guitar_on_order)
    for g, q in guit.items():
        guitar_array.append((g.name, q, g.price * q))

    # <--- payment method
    payment_types = payment_type_model.PaymentType.objects.filter(customer__user = request.user)

    return render(request, 'guitar_zone/order.html', {"guitar": guitar_array, "total": total_price, "payment_types": payment_types})

guitar_zone/views/payment_type_view.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from guitar_zone.forms import PaymentTypeForm



def add_payment(request):
    print("THIS IS REQUEST:",request.user.id)
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = PaymentTypeForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            post = form.save(commit=False)
            post.customer_id = request.user.id


            post.save()
            print("GOT TO SAVE")
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            return HttpResponseRedirect(redirect_to='/guitar_zone/guitars/')

    # if a GET (or any other method) we'll create a blank form
    else:
        form = PaymentTypeForm()

    return render(request, 'guitar_zone/payment_type.html', {'form': form})

guitar_zone/views/rent_out_guitar_view.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from guitar_zone.models.guitar_model import Guitar
from guitar_zone.forms import RentOutGuitarForm

def rent_out_guitar(request):
    print("THIS IS REQUEST:",request.user.id)
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = RentOutGuitarForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            post = form.save(commit=False)
            post.seller_id = request.user.id


            post.save()
            print("GOT TO SAVE")
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            return HttpResponseRedirect(redirect_to='/guitar_zone/guitars/')

    # if a GET (or any other method) we'll create a blank form
    else:
        form = RentOutGuitarForm()

    return render(request, 'guitar_zone/rent_out_guitar.html', {'form': form})

guitar_zone/templates/guitar_zone/base.html
{% load staticfiles %}
<html>
    <head>
        <title>Guitar Zone</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">
        <link href="https://fonts.googleapis.com/css?family=Inconsolata" rel="stylesheet">
    </head>
    <body>
        <body>
            {% url 'guitar_zone:home' as home %}
            {% url 'guitar_zone:guitars' as guitars %}
            {% url 'guitar_zone:addguitar' as addguitar %}
            {% url 'guitar_zone:account' as account %}
            {% url 'guitar_zone:cart' as cart %}
            {% url 'guitar_zone:login' as login %}
            {% url 'guitar_zone:register' as register %}
            {% url 'guitar_zone:logout' as logout %}
            <nav class="navbar navbar-inverse">
              <div class="container-fluid">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                  </button>
                  <a class="navbar-brand" href="{% url 'guitar_zone:home' %}">Guitar Zone</a>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                  <ul class="nav navbar-nav">
                    <li {% if request.path == home %} class = 'active' {% endif %}><a href="{% url 'guitar_zone:home' %}">Home</a></li>
                    <li {% if request.path == guitars %} class = 'active' {% endif %}><a href="{% url 'guitar_zone:guitars' %}">Guitars</a></li>
                    <li {% if request.path == addguitar %} class = 'active' {% endif %}><a href="{% url 'guitar_zone:addguitar' %}">Post Your Guitar</a></li>
                    {% if user.username %}
                    <li style="color: white"><a href="#">Welcome, {{ user.username }}</a></li>
                    {% endif %}
                  </ul>
                  <ul class="nav navbar-nav navbar-right">
                    <li  {% if request.path == cart %} class='active' {% endif %}><a href="{% url 'guitar_zone:cart' %}">Cart<i class="glyphicon glyphicon-shopping-cart"></i><br></a></li>
                    <li  {% if request.path == login %} class='active' {% endif %}><a href="{% url 'guitar_zone:login' %}">Login</a></li>
                    <li  {% if request.path == register %} class='active' {% endif %}><a href="{% url 'guitar_zone:register' %}">Register</a></li>
                    <li  {% if request.path == logout %} class='active' {% endif %}><a href="{% url 'guitar_zone:logout' %}">Logout</a></li>
                  </ul>
                    </li>
                  </ul>
                </div><!-- /.navbar-collapse -->
              </div><!-- /.container-fluid -->
            </nav>
            </div>
            <div class="content container">
                <div class="row">
                    <div class="col-md-8">
                    {% block content %}
                    {% endblock %}
                    </div>
                </div>
            </div>
        </body>
    </body>
</html>

guitar_zone/templates/guitar_zone/guitar_category.html
{% extends 'guitar_zone/base.html' %}

{% block content %}
  <h1 class="no_hover_product_type_header"> {{ guitar_type}} </h1>
  {% for g in guitar_list %}
  <div>
      <a href="{% url 'guitar_zone:guitardetail' g.id %}">
        <h3>{{g.name}}</h3>
      </a>
      <h3>${{g.price}}/day</h3>
  </div>
  {% endfor %}

{% endblock %}

guitar_zone/templates/guitar_zone/guitar_detail.html
{% extends 'guitar_zone/base.html' %}

{% block content %}
    <h1 class="welcome">Guitar Details</h1>
    <h2 class="welcome">{{guitar.name}}</h2>
    <div class="welcome">
        <h3>Description: {{guitar.description}}</h3>
        <h3>Price: ${{guitar.price}}/day</h3>
    {% if user.is_authenticated %}
    <form action="/guitar_zone/add_guitar_to_order/{{guitar.id}}/" method="POST">
    {% csrf_token %}
    <button>Rent This Guitar</button>
    </form>
    {% endif %}
    </div>  

{% endblock %}

guitar_zone/templates/guitar_zone/guitars.html
{% extends 'guitar_zone/base.html' %}

{% block content %}
  <h1 class="welcome">Available Guitars for Rent</h1>
  {% for guit in guitars_info %}
      <a href="{% url 'guitar_zone:guitartype' guit.type_id %}"><h3 class="product_type_header">{{ guit.type_label_name }}({{ guit.count }})</h3></a>
        {% for g in guit.g_list %}
          <div class="welcome">
            <a href="{% url 'guitar_zone:guitardetail' g.id %}"><h4 class="inline">{{ g.name }}</h4></a>
            <p class="inline">${{ g.price }}/day</p>
          </div>
    {% endfor %}
  {% endfor %}
{% endblock %}

guitar_zone/templates/guitar_zone/home.html
{% extends 'guitar_zone/base.html' %}

{% block content %}
  <h1 class="welcome">Welcome to Guitar Zone!</h1>
  <blockquote>
  <h4 class="welcome">Our goal is for local guitarists to have the opportunity to rent other user's guitars for gigs or simply to try out a guitar for personal use. <br>
  <br>Here are a few of the most recent posts from our users:</h4>
  </blockquote>
  {% for gt in guitar_type %}
      <h3 class="no_hover_product_type_header">{{ gt.label_name }}</h3>
      {% for gui in guitar %}
        {% for g in gui %}
        {% if g.guitar_type.pk == gt.pk %}
          <div class="welcome">
            <a href="{% url 'guitar_zone:guitardetail' g.id %}"><h4 class="inline">{{ g.name }}</h4></a>
            <p class="inline">${{ g.price }}/day</p> 
          </div>
      {% endif %}
      {% endfor %}
    {% endfor %}
  {% endfor %}
{% endblock %}

guitar_zone/templates/guitar_zone/login.html
{% extends 'guitar_zone/base.html' %}

{% block content %}
<div class="welcome">
  <h1>Login Existing User</h1>
  <form class="" action="{% url 'guitar_zone:login_customer' %}" method="post">
    {% csrf_token %}
    <input type="text" name="username" value="" placeholder="Email"><br>
    <input type="password" name="password" value="" placeholder="Password"><br>
    <button type="submit" name="button">Submit</button>
  </form>
</div>  
  <div class="welcome">
    <p>Not a current user? Register <a href="{% url 'guitar_zone:register' %}">here</a></p>
  </div>
{% endblock %}

guitar_zone/templates/guitar_zone/order.html
{% extends 'guitar_zone/base.html' %}
{% block content %}
<div class="welcome">
<h2>Cart</h2>
    <table class="table">
    {% for g in guitar %}
        <tr>
            <td><h3>Guitar</h3>{{ g.0 }}
            <h3>Price/day</h3>{{ g.2}}</td>
        <!--{% if not forloop.last and forloop.counter == 3 or forloop.counter == 6 %}-->
        </tr>
        <tr>
        <!--{% endif %}-->
    {% endfor %}
        </tr>
    </table>
<br>
<div class="row">
  <div class="col-sm-3">
    {% if payment_types %}
    <form action="" method="POST">
      {% csrf_token %}
      <div class="form-group">
        <h3><label for="sell">Choose Payment Type:</label></h3>
        <select class="form-control" id="select_payment" name="select_payment" required>
          {% for payment_type in payment_types %}
          <option value="{{payment_type.id}}">{{payment_type.name_on_card}} - {{payment_type.card_number}}
          </option>
          {% endfor %}
        </select>
      </div>
      </br>
      {% endif %}
      <a href="{% url 'guitar_zone:addpayment' %}">Add a payment</a>
    <br>
    </br>
    <button class="btn btn-success">Complete Your Rental</button>    
  </div>
</div>

<h3>Total: ${{total|floatformat:2}}</h3>
</div>
{% endblock %}

guitar_zone/templates/guitar_zone/payment_type.html
{% extends 'guitar_zone/base.html' %}
{% block content %}
<h1 class="welcome">Add Your Credit Card Information</h1> <div>

    <h3 class="welcome">
    <form id="add_payment_type_form" method="post" action="addpayment">
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}
        {% for field in form.visible_fields %} <br><br>
            {{ field.errors }}
            {{ field.help_text }}
            {{ field }}
        {% endfor %}
        </br><br></h3>
        <!-- Hidden Form requests url route from previous page -->
        <input type="hidden" name="next" value="{{ request.GET.next }}">
        <input type="submit" name="submit" value="Add Payment Type" />
    </form>
</div>
{% endblock %}

guitar_zone/templates/guitar_zone/register.html
{% extends 'guitar_zone/base.html' %}

{% block content %}
<div class="welcome">
  <h1>Register New User</h1>
  <h5>*Please use email as username*</h5>
  <form class="" action="{% url 'guitar_zone:register_customer' %}" method="post">
    {% csrf_token %}
    <input type="text" name="username" value="" placeholder="username"></br>
    <br><input type="password" name="password" value="" placeholder="Password"></br>
    <br><input type="text" name="first_name" value="" placeholder="Enter First Name"></br>
    <br><input type="text" name="last_name" value="" placeholder="Enter Last Name"></br>
    <br><input type="text" name="address" value="" placeholder="Enter Address"></br>
    <br><input type="text" name="city" value="" placeholder="Enter City"></br>
    <br><input type="text" name="state_province" value="" placeholder="Enter State/Province"></br>
    <br><input type="text" name="country" value="" placeholder="Enter Country"></br>
    <br><input type="text" name="postal_code" value="" placeholder="Enter Postal Code"></br>
    <br><input type="text" name="email" value="" placeholder="Email"></br>
    <br><button type="submit" name="button">Submit</button>
  </form>
  </div>

{% endblock %}

guitar_zone/templates/guitar_zone/rent_out_guitar.html
{% extends 'guitar_zone/base.html' %}
{% block content %}
{% load staticfiles %}
<h1 class="welcome">Post Your Guitar</h1> 
<div>
    <h4>
    <form id="add_product_form" method="post" action="addproduct" class="welcome">
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}
        {% for field in form.visible_fields %} <br><br>
            {{ field.errors }}
            {{ field.help_text }}
            {{ field }}
            {{ field.guitar_type.label_name }}
        {% endfor %}
        </br><br>
    </h4>
        <!-- Hidden Form requests url route from previous page -->
        <input type="hidden" name="next" value="{{ request.GET.next }}">
        <input type="submit" name="submit" value="Post Guitar" />
    </form>
</div>
{% endblock %}